---
- name: Enable the el7+osp13 repositories 
  hosts: undercloud:overcloud
  serial: 10
  become: yes
  vars:
    rhsm_host: satellite.voltron.xyz
    rhsm_org: VXYZ_Labs
    rhsm_key: vxyz-labs-rhosp13-ak
    rhsm_repos:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-rh-common-rpms
      - rhel-ha-for-rhel-7-server-rpms
      - rhel-7-server-openstack-13-rpms

  tasks:
    - name: Get current Satellite registration status
      command: subscription-manager status
      register: reg_status
      ignore_errors: yes
      changed_when: false
      tags: 
        - satellite_register

    - name: Install katello consumer CA on host if unregistered
      yum:
        name: 'http://{{ rhsm_host }}/pub/katello-ca-consumer-latest.noarch.rpm'
        state: present
      register: result
      until: result is succeeded
      retries: 3
      delay: 5
      when: "'Unknown' in reg_status.stdout"
      tags: 
        - satellite_register

    - name: Enable Satellite Registration if unregistered
      redhat_subscription:
        server_hostname: '{{ rhsm_host }}'
        org_id: '{{ rhsm_org }}'
        activationkey: '{{ rhsm_key }}'
        state: present
        force_register: yes
      retries: 3
      delay: 5
      when: "'Unknown' in reg_status.stdout"
      tags: 
        - satellite_register

    - name: Disable all repositories not required
      rhsm_repository:
        name: '*'
        state: disabled
      tags: repo_enable

    - name: Enable the configured repositories 
      rhsm_repository:
        name: '{{ rhsm_repos }}'
        state: enabled
      tags: repo_enable
