---
- name: Enable the el8+osp16 repositories 
  hosts: undercloud:overcloud
  serial: 10
  become: yes
  vars:
    rhsm_host: satellite.voltron.xyz
    rhsm_org: VXYZ_Labs
    rhsm_key: osp-13-ak
    rhsm_rel_ver: "8.2"
    rhsm_repos_enabled:
      - rhel-8-for-x86_64-baseos-eus-rpms
      - rhel-8-for-x86_64-appstream-eus-rpms
      - rhel-8-for-x86_64-highavailability-eus-rpms
      - openstack-16.1-for-rhel-8-x86_64-rpms
      - ansible-2.9-for-rhel-8-x86_64-rpms
      - advanced-virt-for-rhel-8-x86_64-rpms
      - fast-datapath-for-rhel-8-x86_64-rpms
      - rhceph-4-tools-for-rhel-8-x86_64-rpms
      - rhceph-4-mon-for-rhel-8-x86_64-rpms
      - rhceph-4-osd-for-rhel-8-x86_64-rpms
  tasks:
    - name: Get current Satellite registration status
      command: subscription-manager status
      register: reg_status
      ignore_errors: yes
      changed_when: false
      tags: 
        - satellite_register

    - name: Install katello consumer CA on host if unregistered
      dnf:
        name: 'http://{{ rhsm_host }}/pub/katello-ca-consumer-latest.noarch.rpm'
        state: present
      register: result
      until: result is succeeded
      retries: 3
      delay: 5
      when: "'Unknown' in reg_status.stdout"
      tags: 
        - satellite_register

    - name: Enable Satellite Registration if unregistered
      redhat_subscription:
        server_hostname: '{{ rhsm_host }}'
        org_id: '{{ rhsm_org }}'
        activationkey: '{{ rhsm_key }}'
        state: present
        release: '{{ rhsm_rel_ver }}'
        force_register: yes
      retries: 3
      delay: 5
      when: "'Unknown' in reg_status.stdout"
      tags: 
        - satellite_register

    - name: Disable all repositories not required
      rhsm_repository:
        name: '*'
        state: disabled
      tags: 
        - repo_enable

    - name: Enable the configured repositories 
      rhsm_repository:
        name: '{{ rhsm_repos_enabled }}'
        state: enabled
      tags:
        - repo_enable
