---
- name: "Preparing the Undercloud for the OSP13->OSP 16.1 upgrade"
  hosts: undercloud
  user: stack
  become: yes
  vars:
    prefix: "em"
    rhsm_host: "satellite.voltron.xyz"
  tasks:
   # Pause and prompt the user before starting 
    - name: This will start the Leapp upgrade preparation for this host.
      pause:
        prompt: "Do you want to proceed ? (yes/no)"
      register: confirm_start
      delegate_to: localhost

    - name: "Aborting playbook on user choice..."
      fail:
        msg: "User canceled procedure. Exiting playbook now"
      when: confirm_start.user_input == "no" or confirm_start.user_input == "n"
      delegate_to: localhost

    - name: "[Persistent NIC names fix ] Update udev rules"
      lineinfile:
        line: "SUBSYSTEM==\"net\", ACTION==\"add\", DRIVERS==\"?*\", ATTR{address}==\"{{ ansible_facts[item]['perm_macaddress'] | default(ansible_facts[item]['macaddress']) }}\", NAME=\"{{ item|replace('eth',prefix) }}\""
        path: /etc/udev/rules.d/70-rhosp-persistent-net.rules
        create: True
      with_items: "{{ ansible_interfaces }}"
      when: item.startswith("eth")

    - name: "[Persistent NIC names fix ] Rename eth files"
      block:
        - name: Check that eth files exists
          stat:
            path: /etc/sysconfig/network-scripts/ifcfg-{{ item }}
          register: nic_result
          with_items: "{{ ansible_interfaces }}"
          when: item.startswith("eth")
        - name: Copy nic files using the new prefix
          copy:
            remote_src: True
            src: "{{ item.stat.path }}"
            dest: "{{ item.stat.path|replace('eth',prefix) }}"
          with_items: "{{ nic_result.results }}"
          when: item.item.startswith("eth") and item.stat.exists
        - name: Edit NAME in new network-script files
          lineinfile:
            regexp: "^NAME=.*"
            line: "NAME={{ item.item|replace('eth',prefix) }}"
            path: "{{ item.stat.path|replace('eth',prefix) }}"
          with_items: "{{ nic_result.results }}"
          when: item.item.startswith("eth") and item.stat.exists
        - name: Edit DEVICE in new network-script files
          lineinfile:
            regexp: "^DEVICE=.*"
            line: "DEVICE={{ item.item|replace('eth',prefix) }}"
            path: "{{ item.stat.path|replace('eth',prefix) }}"
          with_items: "{{ nic_result.results }}"
          when: item.item.startswith("eth") and item.stat.exists
        - name: Backup old eth network-script files
          copy:
            remote_src: True
            src: "{{ item.stat.path }}"
            dest: "{{ item.stat.path }}.bak"
          with_items: "{{ nic_result.results }}"
          when: item.item.startswith("eth") and item.stat.exists
        - name: Remove old eth network-script files
          file:
            path: "{{ item.stat.path }}"
            state: absent
          with_items: "{{ nic_result.results }}"
          when: item.item.startswith("eth") and item.stat.exists

    - name: "[Persistent NIC names fix ] Rename route files"
      block:
        - name: Check that route files exists
          stat:
            path: /etc/sysconfig/network-scripts/route-{{ item }}
          register: route_result
          with_items: "{{ ansible_interfaces }}"
          when: item.startswith("eth")
        - name: Copy route files using the new prefix
          copy:
            remote_src: True
            src: "{{ item.stat.path }}"
            dest: "{{ item.stat.path|replace('eth',prefix) }}"
          with_items: "{{ route_result.results }}"
          when: item.item.startswith("eth") and item.stat.exists
        - name: Backup old route files
          copy:
            remote_src: True
            src: "{{ item.stat.path }}"
            dest: "{{ item.stat.path }}.bak"
          with_items: "{{ route_result.results }}"
          when: item.item.startswith("eth") and item.stat.exists
        - name: Remove old route files
          file:
            path: "{{ item.stat.path }}"
            state: absent
          with_items: "{{ route_result.results }}"
          when: item.item.startswith("eth") and item.stat.exists

    - name: Enable PermitRootLogin parameter in /etc/ssh/sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        line: PermitRootLogin yes
        create: yes
   
    - name: Remove the katello-host-tools-fact-plugin package 
      yum:
        name: katello-host-tools-fact-plugin
        state: absent

    - name: Stopping the Undercloud OpenStack services 
      shell: |
        sudo systemctl stop openstack-* httpd haproxy mariadb rabbitmq* docker xinetd
      ignore_errors: true

    - name: Removing OSP13 packages from the Undercloud
      shell: |
        sudo yum -y remove *el7ost* galera* haproxy* \
          httpd mysql* pacemaker* xinetd python-jsonpointer \
          qemu-kvm-common-rhev qemu-img-rhev rabbit* \
          redis* \
          -- \
          -*openvswitch* -python-docker -python-PyMySQL \
          -python-pysocks -python2-asn1crypto -python2-babel \
          -python2-cffi -python2-cryptography -python2-dateutil \
          -python2-idna -python2-ipaddress -python2-jinja2 \
          -python2-jsonpatch -python2-markupsafe -python2-pyOpenSSL \
          -python2-requests -python2-six -python2-urllib3 \
          -python-httplib2 -python-passlib -python2-netaddr -ceph-ansible

    - name: Deleting directories /etc/httpd and /var/lib/docker 
      file:
        path: '{{ item }}'
        state: absent
      loop:
        - /etc/httpd
        - /var/lib/docker

    - name: "[Leapp Install] ensure correct OSP13 repositories enabled in Undercloud"
      tags: satellite_registration
      block:
        - name:  Get registration status
          command: subscription-manager status
          register: reg_status
          ignore_errors: yes
          changed_when: false
        - name: Ensure katello consumer CA installed
          yum:
            name: 'http://{{ rhsm_host }}/pub/katello-ca-consumer-latest.noarch.rpm'
            state: present
          until: result is succeeded
          retries: 10
          delay: 5
          when: "'Unknown' in reg_status.stdout"
        - name: Ensure host registration to Satellite
          redhat_subscription:
            server_hostname: '{{ rhsm_host }}'
            org_id: VXYZ_Labs
            activationkey: osp-13-ak
            state: present
            force_register: yes
        - name: Ensure all repositories disabled
          rhsm_repository:
            name: '*'
            state: disabled
        - name: Ensure specific OSP13 repositories enabled
          rhsm_repository:
            name: '{{ item | join("") }}'
            state: enabled
          loop:
            - rhel-7-server-rpms
            - rhel-7-server-extras-rpms
            - rhel-7-server-rh-common-rpms
            - rhel-ha-for-rhel-7-server-rpms
            - rhel-7-server-openstack-13-rpms
            - rhel-7-server-rhceph-3-tools-rpms

    - name: "[Leapp Install] Ensure Leapp packages installed"
      yum:
        name: leapp
        state: installed
      tags:
        - install_leapp

    - name: "[Leapp Install] Extract required Leapp upgrade files from remote archive"
      unarchive:
        src: 'http://{{ rhsm_host }}/pub/leapp_upgrade/leapp-data12.tar.gz'
        dest: /etc/leapp/files
        remote_src: true
      tags:
        - install_leapp

    - name: "[Leapp Install] Disable Leapp module checks preventing an upgrade"
      command: /usr/bin/leapp answer --add --section '{{ item }}'=True
      loop:
        - 'remove_pam_krb5_module_check.confirm'
        - 'remove_pam_pkcs11_module_check.confirm'
      tags:
        - install_leapp

    - name: "[Leapp Install] Configure Leapp transaction options"
      shell: |
        echo 'openvswitch2.11' | sudo tee -a /etc/leapp/transaction/to_remove;
        echo 'openvswitch2.13' | sudo tee -a /etc/leapp/transaction/to_install;
        echo 'ceph-ansible' | sudo tee -a /etc/leapp/transaction/to_keep;
      tags:
        - install_leapp
 
    - name: Leapp Upgrade Preparation Complete
      debug:
        msg: 
          - "############################################################"
          - "Leapp preparation on the Undercloud completed. Next steps:"
          - "* Reboot Undercloud"
          - "* Perform a Leapp pre-upgrade check: "
          - "  sudo leapp preupgrade --debug --enablerepo rhel-8-for-x86_64-baseos-eus-rpms --enablerepo rhel-8-for-x86_64-appstream-eus-rpms --enablerepo fast-datapath-for-rhel-8-x86_64-rpms --enablerepo ansible-2.9-for-rhel-8-x86_64-rpms"
          - "If successful proceed with the Leapp upgrade on the host:"
          - "  sudo leapp upgrade --debug --enablerepo rhel-8-for-x86_64-baseos-eus-rpms --enablerepo rhel-8-for-x86_64-appstream-eus-rpms --enablerepo fast-datapath-for-rhel-8-x86_64-rpms --enablerepo ansible-2.9-for-rhel-8-x86_64-rpms"
          - "The Leapp upgrade will complete in approximately 30-45 minutes. The Undercloud will be rebooted as a result."
          - "Do not proceed with the Undercloud upgrade until the Leapp upgrade has been completed successfully."
          - "############################################################"
      tags:
        - install_leapp
