---
- name: "Preparing the Overcloud for the OSP13->OSP 16.1 upgrade"
  hosts: overcloud
  user: heat-admin
  become: yes
  vars:
    prefix: "em"
    rhsm_host: "satellite.voltron.xyz"
    rhsm_org: "VXYZ_Labs"
    rhsm_ak: "osp-13-ak"
    rhsm_repos:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-rh-common-rpms
      - rhel-ha-for-rhel-7-server-rpms
      - rhel-7-server-openstack-13-rpms
      - rhel-7-server-rhceph-3-tools-rpms
      - rhel-7-server-rhceph-3-mon-rpms
      - rhel-7-server-rhceph-3-osd-rpms

  tasks:
    - name: "[Leapp install prepare] ensure correct OSP13 repositories enabled"
      tags: satellite_registration
      block:
        - name:  Get registration status
          command: subscription-manager status
          register: reg_status
          ignore_errors: yes
          changed_when: false
        - name: Ensure katello consumer CA installed
          yum:
            name: 'http://{{ rhsm_host }}/pub/katello-ca-consumer-latest.noarch.rpm'
            state: present
          register: result
          until: result is succeeded
          retries: 10
          delay: 5
          when: "'Unknown' in reg_status.stdout"
        - name: Ensure host registration to Satellite
          redhat_subscription:
            server_hostname: '{{ rhsm_host }}'
            org_id: '{{ rhsm_org }}'
            activationkey: '{{ rhsm_ak }}'
            state: present
            force_register: yes
        - name: Ensure all repositories disabled
          rhsm_repository:
            name: '*'
            state: disabled
        - name: Ensure specific OSP13 repositories enabled
          rhsm_repository:
            name: '{{ rhsm_repos }}'
            state: enabled

    - name: "[Persistent NIC names fix ] Update udev rules"
      lineinfile:
        line: "SUBSYSTEM==\"net\", ACTION==\"add\", DRIVERS==\"?*\", ATTR{address}==\"{{ ansible_facts[item]['perm_macaddress'] | default(ansible_facts[item]['macaddress']) }}\", NAME=\"{{ item|replace('eth',prefix) }}\""
        path: /etc/udev/rules.d/70-rhosp-persistent-net.rules
        create: True
      with_items: "{{ ansible_interfaces }}"
      when: item.startswith("eth")

    - name: "[Persistent NIC names fix ] Rename eth files"
      block:
        - name: Check that eth files exists
          stat:
            path: /etc/sysconfig/network-scripts/ifcfg-{{ item }}
          register: nic_result
          with_items: "{{ ansible_interfaces }}"
          when: item.startswith("eth")
        - name: Copy nic files using the new prefix
          copy:
            remote_src: True
            src: "{{ item.stat.path }}"
            dest: "{{ item.stat.path|replace('eth',prefix) }}"
          with_items: "{{ nic_result.results }}"
          when: item.item.startswith("eth") and item.stat.exists
        - name: Edit NAME in new network-script files
          lineinfile:
            regexp: "^NAME=.*"
            line: "NAME={{ item.item|replace('eth',prefix) }}"
            path: "{{ item.stat.path|replace('eth',prefix) }}"
          with_items: "{{ nic_result.results }}"
          when: item.item.startswith("eth") and item.stat.exists
        - name: Edit DEVICE in new network-script files
          lineinfile:
            regexp: "^DEVICE=.*"
            line: "DEVICE={{ item.item|replace('eth',prefix) }}"
            path: "{{ item.stat.path|replace('eth',prefix) }}"
          with_items: "{{ nic_result.results }}"
          when: item.item.startswith("eth") and item.stat.exists
        - name: Backup old eth network-script files
          copy:
            remote_src: True
            src: "{{ item.stat.path }}"
            dest: "{{ item.stat.path }}.bak"
          with_items: "{{ nic_result.results }}"
          when: item.item.startswith("eth") and item.stat.exists
        - name: Remove old eth network-script files
          file:
            path: "{{ item.stat.path }}"
            state: absent
          with_items: "{{ nic_result.results }}"
          when: item.item.startswith("eth") and item.stat.exists

    - name: "[Persistent NIC names fix ] Rename route files"
      block:
        - name: Check that route files exists
          stat:
            path: /etc/sysconfig/network-scripts/route-{{ item }}
          register: route_result
          with_items: "{{ ansible_interfaces }}"
          when: item.startswith("eth")
        - name: Copy route files using the new prefix
          copy:
            remote_src: True
            src: "{{ item.stat.path }}"
            dest: "{{ item.stat.path|replace('eth',prefix) }}"
          with_items: "{{ route_result.results }}"
          when: item.item.startswith("eth") and item.stat.exists
        - name: Backup old route files
          copy:
            remote_src: True
            src: "{{ item.stat.path }}"
            dest: "{{ item.stat.path }}.bak"
          with_items: "{{ route_result.results }}"
          when: item.item.startswith("eth") and item.stat.exists
        - name: Remove old route files
          file:
            path: "{{ item.stat.path }}"
            state: absent
          with_items: "{{ route_result.results }}"
          when: item.item.startswith("eth") and item.stat.exists

    - name: Enable PermitRootLogin parameter in /etc/ssh/sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        line: PermitRootLogin yes
        create: yes
   
    - name: Remove the katello-host-tools-fact-plugin package 
      yum:
        name: katello-host-tools-fact-plugin
        state: absent

    - name: "[Leapp install prepare] Ensure Leapp packages installed"
      yum:
        name: leapp
        state: installed
      tags:
        - install_leapp

    - name: "[Leapp install prepare] Extract required Leapp upgrade files from remote archive"
      unarchive:
        src: 'http://{{ rhsm_host }}/pub/leapp_upgrade/leapp-data12.tar.gz'
        dest: /etc/leapp/files
        remote_src: true
      tags:
        - install_leapp

    - name: "[Leapp install] Disable Leapp module checks preventing an upgrade"
      command: /usr/bin/leapp answer --add --section '{{ item }}'=True
      loop:
        - 'remove_pam_krb5_module_check.confirm'
        - 'remove_pam_pkcs11_module_check.confirm'
      tags:
        - install_leapp

    - name: "[Leapp install] Configure Leapp transaction options"
      shell: |
        echo 'openvswitch2.11' | sudo tee -a /etc/leapp/transaction/to_remove;
        echo 'openvswitch2.13' | sudo tee -a /etc/leapp/transaction/to_install;
        echo 'ceph-ansible' | sudo tee -a /etc/leapp/transaction/to_keep;
      tags:
        - install_leapp
 
    - name: Leapp Upgrade Preparation Complete
      run_once: true
      debug:
        msg: 
          - "############################################################"
          - "Leapp preparation completed. Next steps:"
          - "* Reboot nodes with kernel based nic name changes"
          - "* Begin the Overcloud upgrade preparation "
          - "############################################################"
      tags:
        - install_leapp
